/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from ws_workunits.xml. ***/
/*===================================================*/


export ws_workunits := MODULE

export t_WUPropertyFilter := record
	string Name {xpath('Name')};
	string ExactValue {xpath('ExactValue')};//hidden[1]
	string MinValue {xpath('MinValue')};//hidden[1]
	string MaxValue {xpath('MaxValue')};//hidden[1]
end;

export t_WUScopeFilter := record
	integer MaxDepth {xpath('MaxDepth')};//hidden[1]
	set of string Scopes {xpath('Scopes/Scope'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
	set of string Ids {xpath('Ids/id'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
	set of string ScopeTypes {xpath('ScopeTypes/ScopeType'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
	dataset(t_WUPropertyFilter) PropertyFilters {xpath('PropertyFilters/PropertyFilter'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
end;

export t_WUNestedFilter := record
	unsigned Depth {xpath('Depth')};//hidden[1]
	set of string ScopeTypes {xpath('ScopeTypes/ScopeType'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
end;

export t_WUExtraProperties := record
	string scopeType {xpath('scopeType')};
	set of string Properties {xpath('Properties/Property'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
end;

export t_WUPropertiesToReturn := record
	boolean AllStatistics {xpath('AllStatistics')};
	boolean AllAttributes {xpath('AllAttributes')};
	boolean AllHints {xpath('AllHints')};
	unsigned8 MinVersion {xpath('MinVersion')};//hidden[1]
	string Measure {xpath('Measure')};//hidden[1]
	set of string Properties {xpath('Properties/Property'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
	dataset(t_WUExtraProperties) ExtraProperties {xpath('ExtraProperties/Extra'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
end;

export t_WUScopeOptions := record
	boolean IncludeMatchedScopesInResults {xpath('IncludeMatchedScopesInResults')};
	boolean IncludeScope {xpath('IncludeScope')};
	boolean IncludeId {xpath('IncludeId')};
	boolean IncludeScopeType {xpath('IncludeScopeType')};
end;

export t_WUPropertyOptions := record
	boolean IncludeName {xpath('IncludeName')};
	boolean IncludeRawValue {xpath('IncludeRawValue')};
	boolean IncludeFormatted {xpath('IncludeFormatted')};
	boolean IncludeMeasure {xpath('IncludeMeasure')};
	boolean IncludeCreator {xpath('IncludeCreator')};
	boolean IncludeCreatorType {xpath('IncludeCreatorType')};
end;

export t_WUResponseProperty := record
	string Name {xpath('Name')};//hidden[1]
	string RawValue {xpath('RawValue')};//hidden[1]
	string Formatted {xpath('Formatted')};//hidden[1]
	string Measure {xpath('Measure')};//hidden[1]
	string Creator {xpath('Creator')};//hidden[1]
	string CreatorType {xpath('CreatorType')};//hidden[1]
end;

export t_WUResponseScope := record
	string ScopeName {xpath('ScopeName')};//hidden[1]
	string Id {xpath('Id')};//hidden[1]
	string ScopeType {xpath('ScopeType')};//hidden[1]
	dataset(t_WUResponseProperty) Properties {xpath('Properties/Property'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! //hidden[1]
end;

export t_WUDetailsRequest := record
	string WUID {xpath('WUID')};
	t_WUScopeFilter ScopeFilter {xpath('ScopeFilter')};//hidden[1]
	t_WUNestedFilter NestedFilter {xpath('NestedFilter')};//hidden[1]
	t_WUPropertiesToReturn PropertiesToReturn {xpath('PropertiesToReturn')};//hidden[1]
	string Filter {xpath('Filter')};//hidden[1]
	t_WUScopeOptions ScopeOptions {xpath('ScopeOptions')};//hidden[1]
	t_WUPropertyOptions PropertyOptions {xpath('PropertyOptions')};//hidden[1]
end;

export t_WUDetailsResponse := record
	unsigned8 MaxVersion {xpath('MaxVersion')};
	string WUID {xpath('WUID')};
	dataset(t_WUResponseScope) Scopes {xpath('Scopes/Scope'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
end;

export t_WUDetailsMetaResponse := record
	set of string Statistics {xpath('Statistics/Statistic'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
	set of string Attributes {xpath('Attributes/Attribute'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
	set of string ScopeTypes {xpath('ScopeTypes/ScopeType'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
	set of string Measures {xpath('Measures/Measure'), MAXCOUNT(1)}; // max_count must be specified in ESDL defintion! 
end;


end;

/*** Not to be hand edited (changes will be lost on re-generation) ***/
/*** ECL Interface generated by esdl2ecl version 1.0 from ws_workunits.xml. ***/
/*===================================================*/

